### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by carlosedubarreto** [SysCV/sam-pt#1]
Do you plan to release the code?
if so, do you know when?

Thanks, this work looks great!

**Comment by m43** [comment]
Hej, yes, we plan to release the code this month. Thanks for your interest!

**Comment by iamrajee** [comment]
> Hej, yes, we plan to release the code this month. Thanks for your interest!

Awesome, thanks for your great work!

**Comment by xiaobuding888** [comment]
When will release this week or next week,do you have a timeline?thanks a lot

**Comment by m43** [comment]
Just released, cheers
