### ISSUE TITLE
(sam) D:\computer_vision\sam-pt>python -m demo.demo \frames_path='sam-pt/data/demo_data/bees/' \query_points_path=null \ longest_side_length=1024 frame_stride=1 max_frames=-1 LexerNoViableAltException: \frames_path='sam-pt/data/demo_data/bees/'                            ^ See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details  Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### ISSUE THREAD

**Issue by wang-shuaikang** [SysCV/sam-pt#12]

**Comment by wang-shuaikang** [comment]
(sam) D:\computer_vision\sam-pt>python -m demo.demo \frames_path='sam-pt/data/demo_data/bees/' \query_points_path=null \ longest_side_length=1024 frame_stride=1 max_frames=-1
LexerNoViableAltException: \frames_path='sam-pt/data/demo_data/bees/'
                           ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by wang-shuaikang** [comment]
This has been solved, there is a problem with the path, just change it to an absolute path

**Comment by m43** [comment]
Hej, glad you resolved your issue. Closing this issue now. If you have any further questions or issues, please don't hesitate to open a new one.
