### ISSUE TITLE
How to use mask sampling for tracing?

### ISSUE THREAD

**Issue by Bentonmaster** [SysCV/sam-pt#17]
我阅读了你们的论文，其中提到了通过提供初始帧掩码的方式进行采样，然后进行跟踪的方法。我想要知道你们提供了相关的测试代码吗？如果有提供就太好了
I read your paper which mentions a method of sampling by providing an initial frame mask and then tracking it. I would like to know if you have provided any test code for this? It would be great if you do.

**Comment by m43** [comment]
Hej, thanks for your interest. If you are looking for the point method used to sample points from the mask, it is implemented in the [`extract_kmedoid_points`](https://github.com/SysCV/sam-pt/blob/main/sam_pt/utils/query_points.py#L62-L99) function. If you are looking for the Video Object Segmentation (VOS) code where an initial GT mask is given and tracked throughout the video, then you can look into the documentation on [running the VOS experiments](https://github.com/SysCV/sam-pt/blob/main/docs/04-running-experiments.md#running-vos-experiments) or look directly into the [VOS evaluation script](https://github.com/SysCV/sam-pt/blob/main/sam_pt/vos_eval/eval.py). Have I understood your question correctly? Let me know if I can provide further help!

**Comment by ManuBN786** [comment]
[extract_kmedoid_points](https://github.com/SysCV/sam-pt/blob/main/sam_pt/utils/query_points.py#L62-L99) only gives you the +ve points.

How to get the -ve points using the same algorithm ?

**Comment by m43** [comment]
Hi @ManuBN786, the function `extract_kmedoid_points` also supports sampling negative points when given the inverted mask as input. For example, if the mask is a float tensor, then you invert it with `1 - mask`. For more context, check how we extract the negative points [here](https://github.com/SysCV/sam-pt/blob/a193869a032e1af11f77f86f02fbe85f00b52792/sam_pt/modeling/sam_pt.py#L238-L306). In our experiments, I've always used Mixed Sampling for selecting negative points.
