### ISSUE TITLE
Confused about the key to enter when running demo or test

### ISSUE THREAD

**Issue by frank6200db** [SysCV/sam-pt#19]
Hi, thanks for your efforts and novel ideas.
However, as I am running demo or experiments, I was asked to either enter API or API key not found. (3 options)
Would you kindly provide more detailed tutorial video or instructions?
Thanks again for your time.

**Comment by m43** [comment]
Thank you for your interest in our project. Based on your description, it seems you're being prompted for the W&B (Weights & Biases) API key. W&B is a tool we've integrated for convenient logging, storing logs in the cloud, and accessing them via the browser.

To address this:

1. Sign up for [W&B](https://docs.wandb.ai/quickstart) if you haven't already.
2. Once signed up, you can follow these steps to log in via the command line:

```bash
# Activate your conda environment
conda activate sam-pt

# Install wandb if it isn't already
pip install wandb

# This will prompt you to log in to wandb
wandb login
```

For context, our use of W&B in the demo is [here](https://github.com/SysCV/sam-pt/blob/0dcc74782338f912b52bffa317379c90f03161d6/demo/demo.py#L70-L87) and [here](https://github.com/SysCV/sam-pt/blob/0dcc74782338f912b52bffa317379c90f03161d6/demo/demo.py#L57-L59).
