### ISSUE TITLE
Real-time integration 

### ISSUE THREAD

**Issue by mertikinci** [SysCV/sam-pt#2]
You are not mentioning any time performance results in your paper. Can we use it for segmenting real time ? Are there any fps rates results of your runs or how much time does it takes per frame with your setup ?  

Thanks for your great work,
best wishes,

**Comment by m43** [comment]
Thank you for your interest in our work. Compared to state-of-the-art trackers such as XMem, SAM-based trackers currently do not run in real-time as their bottleneck lies in calling SAM's costly image encoder for each frame independently. On top of this, our method also introduces less costly point tracking. We acknowledge the importance of real-time processing for many applications and will come back to you once we have final and comprehensive inference times.

**Comment by m43** [comment]
We added FPS results in the tables [here](https://github.com/SysCV/sam-pt/blob/33f66f50e5d15900f3672a91a5d7f907aaea4326/docs/04-running-experiments.md#using-different-variants-of-sam), reported for running on an NVIDIA RTX A6000
