### ISSUE TITLE
Add feature points in real time

### ISSUE THREAD

**Issue by ChengWan9** [SysCV/sam-pt#23]
Thanks for your great work！
But when i run sam-pt,I found that sometimes it divided the ground into ranges.
Have you tried adding feature points in subsequent frames?
![image](https://github.com/SysCV/sam-pt/assets/143673887/b1645213-9869-4d34-9316-249494aa2444)

**Comment by m43** [comment]
Hi @gitsawww, thanks for your question. Could you elaborate a bit more on the issue? Maybe you have faced point tracking failures?

If your use case might be to manually annotate data, you might want to consider using SAM-PT for interactive point-based video segmentation. The interactive point-based annotation could look like this:
![Interactive Loading](https://raw.githubusercontent.com/SysCV/sam-pt/main/assets/interactive-loading.gif)

**Comment by ChengWan9** [comment]
thank you!
