### ISSUE TITLE
Tracking ability with a small number of frames

### ISSUE THREAD

**Issue by georgeYanch** [SysCV/sam-pt#25]
Hi again :)
Your work is truly amazing, although, I wonder If model won't be able to work correctly with, for example, 3-5 frame video?

For now, I have an issue when for short sequences I get zero masks and trajectories, scores are -inf.

Could It be a consequence of no object motion?

**Comment by m43** [comment]
Hi, thanks for your questions and issues, and sorry for the delay! I've not covered an edge case of CoTracker being given a small number of frames. This should be resolved with [this commit](https://github.com/SysCV/sam-pt/commit/a193869a032e1af11f77f86f02fbe85f00b52792). Cheers!
