### ISSUE TITLE
How to get evaluation results for DAVIS2016, YouTube2018 and MOSE?

### ISSUE THREAD

**Issue by jameslahm** [SysCV/sam-pt#26]
Thank you for your great work! Would you mind sharing the code to get the evaluation results for DAVIS2016, YouTube2018 and MOSE? Thanks a lot!

**Comment by m43** [comment]
Hi! Thanks for your interest. You can download those datasets as described [here](https://github.com/SysCV/sam-pt/blob/45c7f0c05feec22213dd703bde614edf3b81ce2d/docs/02-prepare-datasets.md). Then, you can run the VOS experiments as described [here](https://github.com/SysCV/sam-pt/blob/45c7f0c05feec22213dd703bde614edf3b81ce2d/docs/04-running-experiments.md#running-vos-experiments). To finally get the evaluation results/scores on the datasets you mentioned, upload the zipped results from the output folder  (e.g., the `eval_D17_val.zip`) to the relevant evaluation server. At the time of writing this, the evaluation servers can be accessed at: [YouTube-VOS 2018](https://codalab.lisn.upsaclay.fr/competitions/7685#participate-submit_results), [MOSE 2023](https://codalab.lisn.upsaclay.fr/competitions/10703#participate-submit_results).

For DAVIS 2016, there is no online evaluation server, but I have now added support within this codebase. Please refer to 
the evaluator script [here](https://github.com/SysCV/sam-pt/blob/45c7f0c05feec22213dd703bde614edf3b81ce2d/sam_pt/vos_eval/davis2017eval.py) as well as the snippet [here](https://github.com/SysCV/sam-pt/blob/45c7f0c05feec22213dd703bde614edf3b81ce2d/sam_pt/vos_eval/eval.py#L440). Note that the [`requirements.txt`](https://github.com/SysCV/sam-pt/blob/main/requirements.txt#L27C1-L27C113) have been updated as well, so you might want to run `pip install -r requirements.txt` for the DAVIS 2016 evaluator to work.

**Comment by jameslahm** [comment]
Thank you!
