### ISSUE TITLE
Error in call to target 'sam_pt.point_tracker.pips.tracker.PipsPointTracker'

### ISSUE THREAD

**Issue by remo-help** [SysCV/sam-pt#27]
Hi! I'm trying to replicate the demo, and I'm running into an issue. I have CUDA 11.8 installed. TensorRT is also installed and can be loaded into python, so I'm not sure what the issue is there.

I tried fresh installs of the environment, CUDA, Tensorflow, Pythorch and TensorRT.

This is the relevant log:

```2023-11-29 19:33:37.255555: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Loading PIPS model from /mnt/sam-pt/models/pips_ckpts/reference_model

reading ckpt from /mnt/sam-pt/models/pips_ckpts/reference_model

Error executing job with overrides: ['frames_path=${hydra:runtime.cwd}/data/demo_data/bees/', 'query_points_path=null', 'longest_side_length=1024', 'frame_stride=1', 'max_frames=-1']

Error in call to target 'sam_pt.point_tracker.pips.tracker.PipsPointTracker':

AssertionError()

full_key: model.point_tracker

```

**Comment by m43** [comment]
Hi! Thanks for reporting this issue and sorry for the delay. From the log snippet you've shared, it appears that an `AssertionError` is being thrown. However, the current details are not comprehensive enough to precisely identify the cause of the failure. To gain a better understanding of the issue, it would be helpful if you could share a more extensive portion of your log output, particularly any error stack trace.

Additionally, I recommend setting the `HYDRA_FULL_ERROR` environment variable to 1 to get a more detailed error log. You can set this variable in your environment by executing `export HYDRA_FULL_ERROR=1` in your terminal before running the demo command.

**Comment by remo-help** [comment]
Hi, thanks for your reply.
Turns out this was an issue on my server. Pip was installing packages for a different python than the one that the virtual environment was using. This issue can be closed
