### ISSUE TITLE
About training spec

### ISSUE THREAD

**Issue by chenshihfang** [SysCV/sam-pt#3]
Hi,

Has this model been implemented without any training process? 
And is the only required training process the training of HQ-SAM independently? 
Alternatively, please provide the GPT/memory usage details for training this model.

Thank you.

**Comment by m43** [comment]
Yes, we use [pre-trained checkpoints](https://github.com/SysCV/sam-pt/blob/33f66f50e5d15900f3672a91a5d7f907aaea4326/docs/03-prepare-checkpoints.md) provided by the respective authors for all point trackers and SAM variants. PIPS is trained exclusively on a synthetic dataset, [FlyingThings++](https://github.com/aharley/pips/blob/486124b4236bb228a20750b496f0fa8aa6343157/README.md#flyingthings-dataset), derived from the FlyingThings optical flow dataset. SAM has been trained on the large-scale [SA-1B dataset](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/README.md#dataset), the largest image segmentation dataset to date. HQ-SAM has been trained on [HQSeg-44K](https://github.com/SysCV/sam-hq/blob/597348543ae88cf8232795df9c741dc9cc6df5b4/train/README.md#1-data-preparation) and we take its pre-trained checkpoints.

**Comment by willshion** [comment]
do you  have wechat app for group learning
