### ISSUE TITLE
detectron2 fails installation

### ISSUE THREAD

**Issue by mfkeles** [SysCV/sam-pt#33]
the latest detectron2 requires pytorch>=1.18 but since the instructions tells us to do `conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.3 -c pytorch` it always fails. 

Installing detectron2 with a torch>=1.8 fails the demo.  Instead using `python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html` to install detectron2 solves this issue.

**Comment by m43** [comment]
We have tested the codebase only with Detectron v0.6 as specified in the [requirements](https://github.com/SysCV/sam-pt/blob/874ff7e73d6ab05418a494d7a02ca233c0b31e8c/requirements.txt#L26), I'm glad you made it work for your setup!
