### ISSUE TITLE
Toolbar not rendering in on MacOS Ventura via X forwarding

### ISSUE THREAD

**Issue by annealai** [SysCV/sam-pt#7]
Can someone post a screenshot of what the toolbar is supposed to contain?

![Screenshot 2023-07-25 at 1 24 54 PM](https://github.com/SysCV/sam-pt/assets/130180176/fbcba20f-5231-4086-86d6-8bf8e8e96cdc)

**Comment by m43** [comment]
Hej, it is the standard Qt-based [cv2 toolbar](https://docs.opencv.org/4.7.0/qtgui.png) that enables simple actions such as zooming, panning, saving a screenshot, etc. I'll disable it to avoid confusion, thanks.
