### ISSUE TITLE
sam_pt.yaml config issue

### ISSUE THREAD

**Issue by SengHongLEE** [SysCV/sam-pt#8]
I've already change the 'use_point_reinit' to true, but it doesn't change at all,still remain false.

**Comment by m43** [comment]
Hej, based on your description, I believe you're [running the demo](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/docs/01-getting-started.md#running-the-interactive-demo). In that case, the model configuration in [`configs/model/sam_pt.yaml`](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/configs/model/sam_pt.yaml#L26) will be overridden in the root configuration [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). Thus, to use point reinitialization in the demo, you can change the `use_point_reinit` to `true` in [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). You can also add a `model.use_point_reinit=true` argument when running the program in the terminal to override the value without modifying `yaml` files.

To delve further into the use of Hydra, you could look into the following resources: 

- The Hydra [getting started guide](https://hydra.cc/docs/1.3/intro/) for a broad overview
- Understanding [how default lists work](https://hydra.cc/docs/1.3/advanced/defaults_list/)
- Learning [the syntax for overrides](https://hydra.cc/docs/1.3/advanced/override_grammar/basic/)

I hope this helps clarify the configs for you!

**Comment by SengHongLEE** [comment]
> Hej, based on your description, I believe you're [running the demo](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/docs/01-getting-started.md#running-the-interactive-demo). In that case, the model configuration in [`configs/model/sam_pt.yaml`](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/configs/model/sam_pt.yaml#L26) will be overridden in the root configuration [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). Thus, to use point reinitialization in the demo, you can change the `use_point_reinit` to `true` in [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). You can also add a `model.use_point_reinit=true` argument when running the program in the terminal to override the value without modifying `yaml` files.
> 
> To delve further into the use of Hydra, you could look into the following resources:
> 
> * The Hydra [getting started guide](https://hydra.cc/docs/1.3/intro/) for a broad overview
> * Understanding [how default lists work](https://hydra.cc/docs/1.3/advanced/defaults_list/)
> * Learning [the syntax for overrides](https://hydra.cc/docs/1.3/advanced/override_grammar/basic/)
> 
> I hope this helps clarify the configs for you!



> Hej, based on your description, I believe you're [running the demo](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/docs/01-getting-started.md#running-the-interactive-demo). In that case, the model configuration in [`configs/model/sam_pt.yaml`](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/configs/model/sam_pt.yaml#L26) will be overridden in the root configuration [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). Thus, to use point reinitialization in the demo, you can change the `use_point_reinit` to `true` in [`configs/demo.yaml`](https://github.com/SysCV/sam-pt/blob/main/configs/demo.yaml#L13). You can also add a `model.use_point_reinit=true` argument when running the program in the terminal to override the value without modifying `yaml` files.
> 
> To delve further into the use of Hydra, you could look into the following resources:
> 
> * The Hydra [getting started guide](https://hydra.cc/docs/1.3/intro/) for a broad overview
> * Understanding [how default lists work](https://hydra.cc/docs/1.3/advanced/defaults_list/)
> * Learning [the syntax for overrides](https://hydra.cc/docs/1.3/advanced/override_grammar/basic/)
> 
> I hope this helps clarify the configs for you!

THANKS for your help. It's solved.
